name = "thaigen-emo-social"
main = "functions/[[route]]" # (ignored by Pages; kept for local wrangler)
compatibility_date = "2024-12-01"


# For local dev with wrangler pages dev --d1
[[d1_databases]]
binding = "DB" # must match code
database_name = "emo_social_db"
database_id = "emo_social_db" # local alias; real ID set in dashboard for Pages


[vars]
JWT_SECRET = "change_me_to_long_random"
MIGRATE_TOKEN = "run_migrations_once"
RPM_BASE = "0.8" # base RPM ($ per 1000 UHV) demo value